//#define PIN__IR        25
//#define PIN__PX        26

#define PIN__MOTOR_IN1 13
#define PIN__MOTOR_IN2 14
#define PIN__MOTOR_IN3 27
#define PIN__MOTOR_IN4 4

#define PIN__LED       15

#define PIN__BTN_A     35, HIGH, GPIO_INPUT::GPIO_BUTTON_PULLUP
#define PIN__BTN_B     -1,  LOW, GPIO_INPUT::GPIO_BUTTON_PULLUP

#define PIN__BATTERY   34,  LOW, GPIO_INPUT::GPIO_ANALOG

#define PIN__SENSOR_OPONENT_RIGHT       32, HIGH, GPIO_INPUT::GPIO_DIGITAL
#define PIN__SENSOR_OPONENT_LEFT        33, HIGH, GPIO_INPUT::GPIO_DIGITAL
#define PIN__SENSOR_OPONENT_SIDE_RIGHT  -1, HIGH, GPIO_INPUT::GPIO_DIGITAL
#define PIN__SENSOR_OPONENT_SIDE_LEFT   -1, HIGH, GPIO_INPUT::GPIO_DIGITAL
#define PIN__SENSOR_LINE                -1,  LOW, GPIO_INPUT::GPIO_DIGITAL